nmi-i2c: Fix unused variable warning
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:29:10: error: ‘buf’ may be used uninitialized [-Werror=maybe-uninitialized]
   29 |   return __builtin___memcpy_chk (__dest, __src, __len,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   30 |                                  __glibc_objsize0 (__dest));
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
../hw/nvme/nmi-i2c.c: In function ‘nmi_handle_message’:
../hw/nvme/nmi-i2c.c:170:14: note: ‘buf’ was declared here
  170 |     uint8_t *buf;
      |              ^~~

We don't have any error return facilities, so just set up a default
case.

Signed-off-by: Jeremy Kerr <jk@codeconstruct.com.au>